//
//  CockpitInformation.swift
//  CockpitTraining
//
//  Created by Umar Patel on 8/20/24.
//

import Foundation


// Experience 1:
let cockpitFeatureDescriptions: [String : String] = ["Navigation_Controls" : "A set of instruments and controls used for plotting the aircraft’s course, including autopilot settings, waypoint entries, and GPS navigation.", "Radar_Display" : "A screen that shows weather patterns, terrain, and other aircraft in the vicinity, assisting the pilot in avoiding hazards and maintaining safe separation.", "Systems_Information_Display" : "A screen that provides real-time data on the aircraft’s systems, including engine performance, fuel levels, and environmental controls.", "Altitude_Indicator" : "This instrument shows the aircraft's altitude above sea level, helping the pilot maintain the desired flight level.", "Direction_Finder" : "A navigational instrument that helps the pilot determine the aircraft's direction relative to a radio beacon or waypoint.", "Primary_Flight_Display" : "The PFD provides crucial flight information, including attitude, altitude, airspeed, and heading, in a single, easy-to-read digital format.", "Brake_Right" : "Located at the top of the rudder pedals, brake pedals control the aircraft's wheel brakes, helping to slow down or stop the aircraft on the ground.", "Brake_Left" : "Located at the top of the rudder pedals, brake pedals control the aircraft's wheel brakes, helping to slow down or stop the aircraft on the ground.", "Rudder_Right" : "The rudder is a vertical control surface on the aircraft's tail, controlled by foot pedals, used to manage yaw and maintain coordinated flight during turns.", "Rudder_Left" : "The rudder is a vertical control surface on the aircraft's tail, controlled by foot pedals, used to manage yaw and maintain coordinated flight during turns.", "Throttle_Right" : "Throttle levers control the engine power output, allowing the pilot to adjust the thrust produced by the engines for speed and altitude management.", "Throttle_Left" : "Throttle levers control the engine power output, allowing the pilot to adjust the thrust produced by the engines for speed and altitude management.", "Yoke_Right" : "Also known as control wheels, yokes are used to steer the aircraft by adjusting the ailerons and elevators, controlling roll and pitch, respectively.", "Yoke_Left" : "Also known as control wheels, yokes are used to steer the aircraft by adjusting the ailerons and elevators, controlling roll and pitch, respectively."]

// Experience 2:
let CockpitFeatureHints: [(String, String)] = [("Rudders", "Foot-operated controls that manage the aircraft's yaw, helping to steer the plane left or right while in flight."), ("Brake Pedals", "Located at the top of the rudder pedals"), ("Throttle Levers", "Hand-operated controls that adjust the engine power, allowing the pilot to manage the speed and climb rate of the aircraft."), ("Control Wheels/Yoke", "The primary control for steering the aircraft, used to adjust the pitch and roll by moving the yoke forward, backward, or side to side."), ("Primary Flight Display", "A digital screen that provides critical flight information, including altitude, airspeed, and attitude, in an easy-to-read format."), ("Direction Finder", "An instrument that helps the pilot determine the aircraft’s heading relative to a radio beacon or waypoint."), ("Altitude Indicator", "Displays the aircraft's altitude above sea level, ensuring that the pilot maintains the desired flight level."), ("Systems Information Display", "A screen that shows real-time data on various aircraft systems, including engine status, fuel levels, and environmental controls."), ("Navigation Controls", "Instruments and inputs used to set and follow the aircraft’s course, including autopilot and GPS settings."), ("Radar Display", "A screen that provides information about surrounding weather patterns, terrain, and nearby aircraft, helping the pilot navigate safely.")]

// This list also has 10 elements, and is a map to the feature hints above. May also be used for experience 3
let CockpitComponentNameMap: [(String, [String])] = [("Rudders", ["Rudder_Left", "Rudder_Right"]), ("Brake Pedals", ["Brake_Left", "Brake_Right"]), ("Throttle Levers", ["Throttle_Left", "Throttle_Right"]), ("Control Wheels/Yoke", ["Yoke_Left", "Yoke_Right"]), ("Primary Flight Display", ["Primary_Flight_Display"]), ("Direction Finder", ["Direction_Finder"]), ("Altitude Indicator", ["Altitude_Indicator"]), ("Systems Information Display", ["Systems_Information_Display"]), ("Navigation Controls", ["Navigation_Controls"]), ("Radar Display", ["Radar_Display"])]


// Experience 3:

let CockpitComponentCommandMap: [(String, [String])] = [("Rudders", ["align rudders to center", "check rudder alignment", "engage rudder control"]), ("Brake Pedals", ["apply brakes", "check brake pressure", "test brake pedals"]), ("Throttle Levers", ["set throttle to idle", "increase throttle to fifty percent", "check throttle response"]), ("Control Wheels/Yoke", ["center control yoke", "test yoke response", "align control wheel"]), ("Primary Flight Display", ["display flight information", "check primary flight display", "activate flight data screen"]), ("Direction Finder", ["set course to waypoint", "activate direction finder", "check heading indicator"]), ("Altitude Indicator", ["check current altitude", "set altitude target", "activate altitude hold"]), ("Systems Information Display", ["display system status", "check systems information", "show engine and fuel data"]), ("Navigation Controls", ["activate autopilot", "set navigation route", "check navigation settings"]), ("Radar Display", ["activate radar", "check radar for obstacles", "display weather radar"])]


